import type { BoardTheme } from "./types";

export const THEMES: BoardTheme[] = [
  {
    id: "classic",
    name: "Classic",
    light: "#e8d5b5",
    dark: "#b58863",
    visitedLight: "#c8b89a",
    visitedDark: "#9a7050",
    current: "#4a6fa5",
    validHighlight: "#7fb86a",
    hintHighlight: "#e8a833",
    knightFill: "#ffffff",
    numberColor: "#ffffff",
    numberBg: "rgba(0, 0, 0, 0.45)",
  },
  {
    id: "chesscom",
    name: "Chess.com",
    light: "#eeeed2",
    dark: "#769656",
    visitedLight: "#d4d4b8",
    visitedDark: "#5e7a44",
    current: "#f6f669",
    validHighlight: "#baca44",
    hintHighlight: "#e8a833",
    knightFill: "#312e2b",
    numberColor: "#ffffff",
    numberBg: "rgba(0, 0, 0, 0.5)",
  },
  {
    id: "ice",
    name: "Ice",
    light: "#dee8f0",
    dark: "#8baac4",
    visitedLight: "#c4d2de",
    visitedDark: "#7090a8",
    current: "#3d7bbf",
    validHighlight: "#6ab3d4",
    hintHighlight: "#e8a833",
    knightFill: "#ffffff",
    numberColor: "#ffffff",
    numberBg: "rgba(30, 60, 100, 0.55)",
  },
  {
    id: "walnut",
    name: "Walnut",
    light: "#c4a882",
    dark: "#7c5c3c",
    visitedLight: "#a89070",
    visitedDark: "#634a2e",
    current: "#d4943a",
    validHighlight: "#a8b455",
    hintHighlight: "#e8a833",
    knightFill: "#ffffff",
    numberColor: "#ffeedd",
    numberBg: "rgba(0, 0, 0, 0.5)",
  },
  {
    id: "neon",
    name: "Neon",
    light: "#2a2a3a",
    dark: "#1a1a28",
    visitedLight: "#222230",
    visitedDark: "#161622",
    current: "#00e5ff",
    validHighlight: "#1a3a3a",
    hintHighlight: "#3a3a1a",
    knightFill: "#00e5ff",
    numberColor: "#00e5ff",
    numberBg: "rgba(0, 229, 255, 0.15)",
  },
];

export const DEFAULT_THEME = THEMES[0]!;
