import type { BoardTheme } from "./types";

export const THEMES: BoardTheme[] = [
  {
    id: "classic",
    name: "Classic",
    light: "#e8d5b5",
    dark: "#b58863",
    visitedLight: "#c8b89a",
    visitedDark: "#9a7050",
    current: "#4a6fa5",
    validHighlight: "#7fb86a",
    hintHighlight: "#e8a833",
    knightFill: "#ffffff",
    numberColor: "#ffffff",
    numberBg: "rgba(0, 0, 0, 0.45)",
  },
  {
    id: "chesscom",
    name: "Chess.com",
    light: "#eeeed2",
    dark: "#769656",
    visitedLight: "#d4d4b8",
    visitedDark: "#5e7a44",
    current: "#f6f669",
    validHighlight: "#baca44",
    hintHighlight: "#e8a833",
    knightFill: "#312e2b",
    numberColor: "#ffffff",
    numberBg: "rgba(0, 0, 0, 0.5)",
  },
  {
    id: "ice",
    name: "Ice",
    light: "#dee8f0",
    dark: "#8baac4",
    visitedLight: "#c4d2de",
    visitedDark: "#7090a8",
    current: "#3d7bbf",
    validHighlight: "#6ab3d4",
    hintHighlight: "#e8a833",
    knightFill: "#ffffff",
    numberColor: "#ffffff",
    numberBg: "rgba(30, 60, 100, 0.55)",
  },
  {
    id: "rose",
    name: "Rose",
    light: "#f0d8e0",
    dark: "#c47a8f",
    visitedLight: "#d8c0c8",
    visitedDark: "#a86478",
    current: "#e84393",
    validHighlight: "#d4a0d0",
    hintHighlight: "#f0a050",
    knightFill: "#ffffff",
    numberColor: "#ffffff",
    numberBg: "rgba(100, 20, 60, 0.5)",
  },
  {
    id: "emerald",
    name: "Emerald",
    light: "#f0ead6",
    dark: "#2d6b4f",
    visitedLight: "#d6d0bc",
    visitedDark: "#1e5a3e",
    current: "#50c878",
    validHighlight: "#a8d8a0",
    hintHighlight: "#e8c840",
    knightFill: "#ffffff",
    numberColor: "#ffffff",
    numberBg: "rgba(0, 40, 20, 0.55)",
  },
  {
    id: "midnight",
    name: "Midnight",
    light: "#b0b8c8",
    dark: "#3a4560",
    visitedLight: "#969eae",
    visitedDark: "#2e3850",
    current: "#6c9bcf",
    validHighlight: "#7a8ab8",
    hintHighlight: "#e8a833",
    knightFill: "#ffffff",
    numberColor: "#ffffff",
    numberBg: "rgba(20, 30, 60, 0.55)",
  },
  {
    id: "coral",
    name: "Coral",
    light: "#fce4d6",
    dark: "#d4806a",
    visitedLight: "#e0ccbe",
    visitedDark: "#b86a56",
    current: "#ff6b6b",
    validHighlight: "#f0b090",
    hintHighlight: "#f0c040",
    knightFill: "#ffffff",
    numberColor: "#ffffff",
    numberBg: "rgba(80, 30, 10, 0.5)",
  },
];

export const DEFAULT_THEME = THEMES[0]!;
